### ISSUE TITLE
Game Crush - 1.19.2 forge

### ISSUE THREAD

**Issue by exdj158** [SistrScarlet/LittleMaidReBirth-Fabric#15]
version: 1.19.2
forge: 43.2.3

[18Jan2023 00:12:00.598] [Structurize IO Worker #1/WARN] [structurize/]: Finished discovering Client Structure packs
[181月2023 00:12:01.114] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:164) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109517_(LevelRenderer.java:1439) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	at net.minecraft.client.renderer.LevelRenderer.invokeRenderEntity(LevelRenderer.java) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	at net.coderbot.iris.pipeline.ShadowRenderer.renderEntities(ShadowRenderer.java:583) ~[oculus-mc1.19.2-1.2.8a.jar%23599!/:?]
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:464) ~[oculus-mc1.19.2-1.2.8a.jar%23599!/:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:631) ~[oculus-mc1.19.2-1.2.8a.jar%23599!/:?]
	at net.minecraft.client.renderer.LevelRenderer.handler$zlj000$iris$renderTerrainShadows(LevelRenderer.java:9661) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1158) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1068) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:840) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.3.jar%23144!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23131!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23131!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23131!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23131!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23131!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23131!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23131!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/LivingEntity
	at net.blacklab.lmr.ModelLittleMaid_Beverly7.setRotationAngles(ModelLittleMaid_Beverly7.java:450) ~[?:?]
	at net.sistr.littlemaidmodelloader.maidmodel.ModelMultiBase.setAngles(ModelMultiBase.java:158) ~[LMML-1.19.2-5.1.1-Forge.jar%23562!/:?]
	at net.sistr.littlemaidmodelloader.client.renderer.MultiModel.lambda$setAngles$1(MultiModel.java:30) ~[LMML-1.19.2-5.1.1-Forge.jar%23562!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.sistr.littlemaidmodelloader.client.renderer.MultiModel.setAngles(MultiModel.java:30) ~[LMML-1.19.2-5.1.1-Forge.jar%23562!/:?]
	at net.sistr.littlemaidrebirth.client.LMMultiModel.setAngles(LMMultiModel.java:32) ~[LMRB-1.19.2-5.3.2-Forge.jar%23563!/:?]
	at net.sistr.littlemaidrebirth.client.LMMultiModel.m_6973_(LMMultiModel.java:19) ~[LMRB-1.19.2-5.3.2-Forge.jar%23563!/:?]
	at net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:117) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	at net.minecraft.client.renderer.entity.MobRenderer.m_7392_(MobRenderer.java:45) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	at net.sistr.littlemaidrebirth.client.MaidModelRenderer.render(MaidModelRenderer.java:75) ~[LMRB-1.19.2-5.3.2-Forge.jar%23563!/:?]
	at net.sistr.littlemaidrebirth.client.MaidModelRenderer.m_7392_(MaidModelRenderer.java:30) ~[LMRB-1.19.2-5.3.2-Forge.jar%23563!/:?]
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:136) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	... 32 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.LivingEntity:inputstream:net/minecraft/entity/LivingEntity.class
	at net.sistr.littlemaidmodelloader.resource.classloader.MultiModelClassLoader.findClass(MultiModelClassLoader.java:56) ~[LMML-1.19.2-5.1.1-Forge.jar%23562!/:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at net.sistr.littlemaidmodelloader.resource.classloader.MultiModelClassLoader.loadClass(MultiModelClassLoader.java:83) ~[LMML-1.19.2-5.1.1-Forge.jar%23562!/:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.blacklab.lmr.ModelLittleMaid_Beverly7.setRotationAngles(ModelLittleMaid_Beverly7.java:450) ~[?:?]
	at net.sistr.littlemaidmodelloader.maidmodel.ModelMultiBase.setAngles(ModelMultiBase.java:158) ~[LMML-1.19.2-5.1.1-Forge.jar%23562!/:?]
	at net.sistr.littlemaidmodelloader.client.renderer.MultiModel.lambda$setAngles$1(MultiModel.java:30) ~[LMML-1.19.2-5.1.1-Forge.jar%23562!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.sistr.littlemaidmodelloader.client.renderer.MultiModel.setAngles(MultiModel.java:30) ~[LMML-1.19.2-5.1.1-Forge.jar%23562!/:?]
	at net.sistr.littlemaidrebirth.client.LMMultiModel.setAngles(LMMultiModel.java:32) ~[LMRB-1.19.2-5.3.2-Forge.jar%23563!/:?]
	at net.sistr.littlemaidrebirth.client.LMMultiModel.m_6973_(LMMultiModel.java:19) ~[LMRB-1.19.2-5.3.2-Forge.jar%23563!/:?]
	at net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:117) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	at net.minecraft.client.renderer.entity.MobRenderer.m_7392_(MobRenderer.java:45) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	at net.sistr.littlemaidrebirth.client.MaidModelRenderer.render(MaidModelRenderer.java:75) ~[LMRB-1.19.2-5.3.2-Forge.jar%23563!/:?]
	at net.sistr.littlemaidrebirth.client.MaidModelRenderer.m_7392_(MaidModelRenderer.java:30) ~[LMRB-1.19.2-5.3.2-Forge.jar%23563!/:?]
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:136) ~[client-1.19.2-20220805.130853-srg.jar%23685!/:?]
	... 32 more
[181月2023 00:12:01.124] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 5201f463-c868-4f36-91df-08fc1d961b5a

**Comment by SistrScarlet** [comment]
導入しているすべてのModのバージョンと、クラッシュが発生した状況を書いてください。
